### ISSUE TITLE
Model problem - UAObjectType already declared

### ISSUE THREAD

**Issue by biancode** [node-opcua/node-opcua-isa95#1]
``` javascript
            var weldingRobotClassType = serverAddressSpace.addEquipmentClassType({
                browseName: "WeldingRobotClassType",
                equipmentLevel: opcua.ISA95.EquipmentLevel.EquipmentModule
            });

            var assemblingRobotClassType = serverAddressSpace.addEquipmentClassType({
                browseName: "AssemblingRobotClassType",
                equipmentLevel: opcua.ISA95.EquipmentLevel.EquipmentModule
            });

            var multiPurposeRobotType = serverAddressSpace.addEquipmentClassType({
                browseName: "MultiPurposeRobotType",
                definedByEquipmentClass: [
                    weldingRobotClassType,
                    assemblingRobotClassType
                ]
            });
```

**Comment by biancode** [comment]
```
14 Aug 19:15:32 - [red] Uncaught Exception:
14 Aug 19:15:32 - AssertionError: !self._objectTypeMap[key], " UAObjectType already declared"
    at _registerObjectType (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/node_modules/node-opcua/lib/address_space/address_space.js:145:5)
    at AddressSpace._register (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/node_modules/node-opcua/lib/address_space/address_space.js:193:9)
    at AddressSpace._createNode (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/node_modules/node-opcua/lib/address_space/address_space.js:365:10)
    at AddressSpace._addObjectOrVariableType (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/node_modules/node-opcua/lib/address_space/address_space.js:1000:27)
    at AddressSpace.addObjectType (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/node_modules/node-opcua/lib/address_space/address_space.js:1033:17)
    at AddressSpace.opcua.AddressSpace.addEquipmentClassType (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/node_modules/node-opcua-isa95/lib/isa95_address_space_extension_equipment.js:38:50)
    at p (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/isa/ISA95-OPCUA-Server.js:1:763)
    at m (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/isa/ISA95-OPCUA-Server.js:1:2093)
    at v (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/isa/ISA95-OPCUA-Server.js:1:4056)
    at Immediate._onImmediate (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/node_modules/node-opcua/lib/server/opcua_server.js:442:9)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by biancode** [comment]
```
        var weldingRobot = serverAddressSpace.addEquipment({
            browseName: "WeldingRobot"
        });

        var robotController = serverAddressSpace.addEquipment({
            browseName: "RobotController",
            containedByEquipment: weldingRobot
        });

        var robotArm = serverAddressSpace.addEquipment({
            browseName: "RobotArm",
            containedByEquipment: weldingRobot
        });
```

starting server works ...  but

**Comment by biancode** [comment]
adding that:

```
        var fanuc_robotArcMate = serverAddressSpace.addPhysicalAssetType({
            browseName: "ArcMate 100iB/6S i",
            modelNumber: "ArcMate 100iB/6S i",
            manufacturer: {
                dataType: "String",
                value: { dataType: opcua.DataType.String, value: "Fanuc Inc"}
            }
        });
```

same error:

```
14 Aug 19:20:58 - [red] Uncaught Exception:
14 Aug 19:20:58 - AssertionError: !self._objectTypeMap[key], " UAObjectType already declared"
    at _registerObjectType (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/node_modules/node-opcua/lib/address_space/address_space.js:145:5)
    at AddressSpace._register (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/node_modules/node-opcua/lib/address_space/address_space.js:193:9)
    at AddressSpace._createNode (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/node_modules/node-opcua/lib/address_space/address_space.js:365:10)
    at AddressSpace._addObjectOrVariableType (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/node_modules/node-opcua/lib/address_space/address_space.js:1000:27)
    at AddressSpace.addObjectType (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/node_modules/node-opcua/lib/address_space/address_space.js:1033:17)
    at AddressSpace.opcua.AddressSpace.addPhysicalAssetType (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/node_modules/node-opcua-isa95/lib/isa95_address_space_extension_physical_asset.js:77:49)
    at p (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/isa/ISA95-OPCUA-Server.js:1:943)
    at m (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/isa/ISA95-OPCUA-Server.js:1:2118)
    at v (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/isa/ISA95-OPCUA-Server.js:1:4081)
    at Immediate._onImmediate (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/node_modules/node-opcua/lib/server/opcua_server.js:442:9)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by erossignon** [comment]
Can you provide a self contained minimalist gist that reproduce the issue ?
It looks like you're calling serverAddressSpace. addPhysicalAssetType  twice with the same browseName.
Btw , this assert/exception is good as it should help you finding unexpected use in the code.

**Comment by biancode** [comment]
https://github.com/biancode/node-red-contrib-isa

Is that OK for you?

https://github.com/biancode/node-red-contrib-isa/blob/master/src/ISA95-OPCUA-Server.js

**Comment by erossignon** [comment]
The code is difficult to trace due to the fact that isa/ISA95-OPCUA-Server.js has been minified.

```
at p (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/isa/ISA95-OPCUA-Server.js:1:943)
    at m (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/isa/ISA95-OPCUA-Server.js:1:2118)
    at v (/Users/klaus/.npm-global/lib/node_modules/node-red-contrib-isa/isa
```

**Comment by biancode** [comment]
with the next pull it will not be minified anymore

**Comment by biancode** [comment]
your helpers/...demo.js works, if it is loaded, but I couldn't find the real diff between file loading and direct adding. It is pushed to the repo of the isa nodes.

![screenshot 2016-08-14 at 09 32 19 pm](https://cloud.githubusercontent.com/assets/4369867/17651405/ad8a4590-6266-11e6-9331-e47028f74740.png)

**Comment by erossignon** [comment]
addPhysicalAssetType({ browseName: "Foo" } can only be called once. can you change the browseName to something else ?
