### ISSUE TITLE
Invalid Version Error

### ISSUE THREAD

**Issue by cannonkalra** [node-opcua/node-opcua-isa95#5]
It's not working with the latest node-opcua

     
           TypeError: Invalid Version: undefined
            at new SemVer (C:\Users\CannonKalra\Desktop\learning\node-opcua-client\opcua-server-aggregation\node_modules\node-opcua-isa95\node_modules\semver\semver.js:314:11)
            at compare (C:\Users\CannonKalra\Desktop\learning\node-opcua-client\opcua-server-aggregation\node_modules\node-opcua-isa95\node_modules\semver\semver.js:647:10)
            at Function.lt (C:\Users\CannonKalra\Desktop\learning\node-opcua-client\opcua-server-aggregation\node_modules\node-opcua-isa95\node_modules\semver\semver.js:688:10)
            at Object.exports.install (C:\Users\CannonKalra\Desktop\learning\node-opcua-client\opcua-server-aggregation\node_modules\node-opcua-isa95\lib\isa95_address_space_extension.js:16:16)
            at module.exports (C:\Users\CannonKalra\Desktop\learning\node-opcua-client\opcua-server-aggregation\node_modules\node-opcua-isa95\index.js:6:52)       
            at Object.<anonymous> (C:\Users\CannonKalra\Desktop\learning\node-opcua-client\opcua-server-aggregation\src\example.js:6:28)
            at Module._compile (internal/modules/cjs/loader.js:1156:30)
            at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
            at Module.load (internal/modules/cjs/loader.js:1000:32)
            at Function.Module._load (internal/modules/cjs/loader.js:899:14)
            [nodemon] app crashed - waiting for file changes before starting...

**Comment by biancode** [comment]
that package is since node-red-contrib-iiot-opcua part of the IIoT package
